POST http://localhost:5000/api/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "test"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

###
GET http://localhost:5000/api/users
Authorization: Bearer access_token

###
GET http://localhost:5000/api/auth/refresh_token

###
DELETE http://localhost:5000/api/auth/refresh_token